baseURL = "hu921.github.io/"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "The Fingers Behind the Page"
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "January 2, 2023"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = false
delayDisqus = false
showRelatedPosts = true
summaryLength  = "9"
gcse = false
Lastmod = false
rss = false 
pagination = "10"
hideAuthor = true
authorInfo = "A curious nomad with a passion for technology, a love for travel and food, and a penchant for building things from bricks and bits"
description="Welcome to my digital diary, where I share my thoughts, life, and passions with the world."


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Author]
  name = "Sara Hu"
  website = "https://isarahu.com"
  email = "husara@gmail.com"
  #facebook = "username"
  instagram = "rebel_gozila"
  #youtube = "user/username" # or channel/channelname
  #twitter = "username"
  #threads = "username"
  linkedin = "husara"
  #github = "username"
  #gitlab = "username"
  #bitbucket = "username"
  #reddit = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

#[[menu.main]]
#    name = "Home"
#    url = "https://isarahu.com"
#    weight = 1

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 2

#[[menu.main]]
#    name = "Notes"
#    url = "/notes/"
#    weight = 3

#[[menu.main]]
#    name = "Tags"
#    url = "/tags/blog/"
#    weight = 4

#[[menu.main]]
#    name = "Collections"
#    url = "/collections/"
#    weight = 5

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6



theme = 'lightbi-hugo'
